### ISSUE TITLE
Contact form not working on submit - An error occurred while sending the message, please try again.

### ISSUE THREAD

**Issue by mellsaid** [PrestaShop/contactform#28] opened 2018-10-03 22:20 UTC
Hello, 

Prestashop 1.7.4.2 
Affected: Contact form
Issue: any customer attempting to post a comment in contact-us page, is getting an error: An error occurred while sending the message, please try again.

After some digging, pulled the error as attached below:
![image](https://user-images.githubusercontent.com/22168697/46442787-c6c01680-c762-11e8-8c39-728129798420.png)
Any ideas on a temporary fix till this is resolved?

This happens for both signed and non-signed customers.

**Comment by khouloudbelguith** [comment] 2018-10-04 09:37
Hi @mellsaid,

Have you the same issue with this ticket: https://github.com/PrestaShop/PrestaShop/issues/9566?
Thanks!

**Comment by mellsaid** [comment] 2018-10-04 09:41
Actually yes - looks the same

**Comment by khouloudbelguith** [comment] 2018-10-04 09:56
@mellsaid, thanks for your feedback.
We are aware of this issue, it is added to our bug roadmap.
Your ticket is a duplicate of #PrestaShop/PrestaShop#9566
So, I close it.
Thanks!

**Comment by khouloudbelguith** [comment] 2018-10-04 09:57
Duplicate of https://github.com/PrestaShop/PrestaShop/issues/9566

**Closed by khouloudbelguith** 2018-10-04 09:56 UTC
