### ISSUE TITLE
An error occurs while sending the message, please try again

### ISSUE THREAD

**Issue by Mreco83** [PrestaShop/contactform#24] opened 2018-05-28 12:10 UTC
Hello. After the last update of the module, when sending a message there is an error "An error occurs while sending the message, please try again".

**Comment by cereal-s** [comment] 2018-07-06 18:05
Same error stated by MaxL on 1.7.3.3. Is there any suggestion on how to solve? Thank you.

**Comment by gnujeremie** [comment] 2018-08-03 14:01
Thanks, had the issue after installing the module because upgrading PS to 1.7.3.x broke the page.
I can't believe theses kind of bugs can happen. 👎

**Comment by matks** [comment] 2018-08-06 08:47
Hello, thank you for the feedback !

If I understand correctly, you are running 1.7.2.x or 1.7.3.x shop but the latest version of the module does not work on your shop, and you installed this version between May and July ?

**Comment by gnujeremie** [comment] 2018-08-06 08:50
Yes, I was running 2 shops (1.7.3.2), and for both of them I had to manually install (.zip) the contactform module. And then, I had to update the template file in order to add 2 news hidden inputs (url & token).

**Comment by MaxL** [comment] 2018-08-06 09:10
actually @matks I think, at least in my case the isse was that i had overridden the template `contactform.tpl` and forgotten to include the added hidden "token" and "url" fields after the update.
on a side note: does the "url" field need to be of type "test" and hidden with css? couldn't it just be of type "hidden"?

**Comment by colinegin** [comment] 2019-10-07 13:53
Hello @khouloudbelguith,

do you still reproduce this issue ?

**Comment by khouloudbelguith** [comment] 2019-10-07 14:06
Hi @colinegin,

No, I tried with PS1.7.6.1 & the `contactform` module v4.1.1., it is OK.
The alert is not displayed.
This issue is duplicated of https://github.com/PrestaShop/PrestaShop/issues/9566, it is randomly reproduced previously.

Thanks!

**Comment by colinegin** [comment] 2019-10-07 14:08
Alright, thanks for your feedback @khouloudbelguith.
Since it is a duplicate, I will close this issue. Please follow and comment PrestaShop/PrestaShop#9566 if needed.

Thanks !

**Closed by colinegin** 2019-10-07 14:08 UTC
